#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

use Interop\Container\ContainerInterface;
use WebsiteMonitoring\Checker\ImprintPage;
use WebsiteMonitoring\Checker\PrivacyPage;
use WebsiteMonitoring\Checker\SitemapBlacklist;
use WebsiteMonitoring\CheckerPluginManager;
use WebsiteMonitoring\ConsoleCommand\CheckCommand;
use WebsiteMonitoring\ConsoleCommand\CommandFactory;
use WebsiteMonitoring\ConsoleCommand\ParseCommand;

$serviceManager = new \Zend\ServiceManager\ServiceManager();
$serviceManager->addAbstractFactory(CommandFactory::class);
$serviceManager->setFactory(CheckerPluginManager::class, function(ContainerInterface $container) {
    return new CheckerPluginManager($container, [
        'invokables' => [
            'imprint-page'      => ImprintPage::class,
            'privacy-page'      => PrivacyPage::class,
            'sitemap-blacklist' => SitemapBlacklist::class,
        ],
    ]);
});

$app = new \Symfony\Component\Console\Application('Website monitoring', '1.0.0');
$app->addCommands([$serviceManager->get(ParseCommand::class), $serviceManager->get(CheckCommand::class)]);
$app->run();
