#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

use Interop\Container\ContainerInterface;
use WebsiteMonitoring\Checker\Content;
use WebsiteMonitoring\Checker\PageExists;
use WebsiteMonitoring\Checker\RobotsTxt;
use WebsiteMonitoring\Checker\SitemapBlacklist;
use WebsiteMonitoring\CheckerPluginManager;
use WebsiteMonitoring\ConsoleCommand\CheckCommand;
use WebsiteMonitoring\ConsoleCommand\CommandFactory;
use WebsiteMonitoring\ConsoleCommand\ParseCommand;

$serviceManager = new \Zend\ServiceManager\ServiceManager();
$serviceManager->addAbstractFactory(CommandFactory::class);
$serviceManager->setFactory(CheckerPluginManager::class, function (ContainerInterface $container) {
    return new CheckerPluginManager($container, [
        'invokables' => [
            'page-exists'       => PageExists::class,
            'robots-txt'        => RobotsTxt::class,
            'sitemap-blacklist' => SitemapBlacklist::class,
            'content'           => Content::class,
        ],
    ]);
});

$app = new \Symfony\Component\Console\Application('Website monitoring', '1.0.0');
$app->addCommands([$serviceManager->get(ParseCommand::class), $serviceManager->get(CheckCommand::class)]);
$app->run();
